<?php $rejoinerHelper = $this->getRejoinerHelper() ?>

<!-- Rejoiner Conversion  -->
<script type="text/javascript">
    var _rejoiner = _rejoiner || [];
    _rejoiner.push(["setAccount", "<?php echo $rejoinerHelper->getRejoinerSiteId() ?>"]);
    _rejoiner.push(["setDomain", "<?php echo $rejoinerHelper->getDomain() ?>"]);
    _rejoiner.push(["sendConversion"]);

    (function() {
        var s = document.createElement('script'); s.type = 'text/javascript';
        s.async = true; s.src = 'https://s3.amazonaws.com/rejoiner/js/v3/t.js';
        var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
    })();
</script>
<!-- End Rejoiner Conversion -->
